/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef asty_gw_plat_service_CONSTANTS_H
#define asty_gw_plat_service_CONSTANTS_H

#include "asty_gw_plat_service_types.h"

namespace asty_gw_sdk {

class asty_gw_plat_serviceConstants {
 public:
  asty_gw_plat_serviceConstants();

};

extern const asty_gw_plat_serviceConstants g_asty_gw_plat_service_constants;

} // namespace

#endif
