/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "asty_gw_plat_service_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace asty_gw_sdk {

} // namespace
