// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AstyGwPlatformSever.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::asty_gw_sdk;

class AstyGwPlatformSeverHandler : virtual public AstyGwPlatformSeverIf {
 public:
  AstyGwPlatformSeverHandler() {
    // Your initialization goes here
  }

  bool ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void device_online( ::asty_gw_sdk::AstyGwMsgResponse& _return, const  ::asty_gw_sdk::AstyGwMsgRequest& request) {
    // Your implementation goes here
    printf("device_online\n");
  }

  void device_register( ::asty_gw_sdk::AstyGwMsgResponse& _return, const  ::asty_gw_sdk::AstyGwMsgRequest& request) {
    // Your implementation goes here
    printf("device_register\n");
  }

  void get_mq_host( ::asty_gw_sdk::AstyGwMsgResponse& _return, const  ::asty_gw_sdk::AstyGwMsgRequest& request) {
    // Your implementation goes here
    printf("get_mq_host\n");
  }

  void request( ::asty_gw_sdk::AstyGwMsgResponse& _return, const  ::asty_gw_sdk::AstyGwMsgRequest& request) {
    // Your implementation goes here
    printf("request\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<AstyGwPlatformSeverHandler> handler(new AstyGwPlatformSeverHandler());
  ::std::shared_ptr<TProcessor> processor(new AstyGwPlatformSeverProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

