/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "asty_gw_device_service_constants.h"

namespace asty_gw_sdk {

const asty_gw_device_serviceConstants g_asty_gw_device_service_constants;

asty_gw_device_serviceConstants::asty_gw_device_serviceConstants() {
}

} // namespace

