// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AstyGwDeviceSever.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::asty_gw_sdk;

class AstyGwDeviceSeverHandler : virtual public AstyGwDeviceSeverIf {
 public:
  AstyGwDeviceSeverHandler() {
    // Your initialization goes here
  }

  void request( ::asty_gw_sdk::AstyGwMsgResponse& _return, const  ::asty_gw_sdk::AstyGwMsgRequest& request) {
    // Your implementation goes here
    printf("request\n");
  }

  void user_bind( ::asty_gw_sdk::AstyGwMsgResponse& _return, const  ::asty_gw_sdk::AstyGwMsgRequest& request) {
    // Your implementation goes here
    printf("user_bind\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<AstyGwDeviceSeverHandler> handler(new AstyGwDeviceSeverHandler());
  ::std::shared_ptr<TProcessor> processor(new AstyGwDeviceSeverProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

